MACOSX_SDK_VERSION:        # [osx]
  - '15.5'                 # [osx]

# https://github.com/conda-forge/admin-requests#larger-runners-for-github-actions
# https://github.com/conda-forge/.cirun
github_actions_labels:
- blacksmith-8vcpu-ubuntu-2404  # [linux64]
- blacksmith-8vcpu-ubuntu-2404-arm  # [linux and aarch64]
- blacksmith-6vcpu-macos-latest  # [osx]
- blacksmith-8vcpu-windows-2025  # [win]
