{% set name = "qt-webengine" %}
{% set version = "5.15.8" %}
{% set version_major_minor = '.'.join(version.split('.')[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version_major_minor }}/{{ version }}/submodules/qtwebengine-everywhere-opensource-src-{{ version }}.tar.xz
    sha256: 4f56dcab592a8e44c93951fb9d4840b5f73fd80ec2776979d38e42abca2b61e3
    patches:
      - patches/0001-aarch64-sys-state-structs.patch                             # [aarch64]
      - patches/0002-macos-fatal-warnings.patch                                  # [osx]
      - patches/0003-Set-host-and-target-cpus-in-gn-build.patch                  # [arm64]
      - patches/0005-macos-use-CONDA_BUILD_SYSROOT.patch                         # [osx]
      - patches/0007-Compile-GN-to-support-both-x86_64-and-arm64-archs-wh.patch  # [arm64]
      # https://bugreports.qt.io/browse/QTBUG-101995?focusedCommentId=653798
      # https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/402639
      - patches/fix_unused_var_in_harfbuzz_ng.patch
      # This patch may be required for other OSes too
      # similar to the discussion in
      # https://github.com/abseil/abseil-cpp/issues/1275
      - patches/limits_h_header.patch
      # Only used in aarch64 / osx-arm
      # https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236855#c8
      #    reverts
      # https://github.com/qt/qtwebengine-chromium/commit/b2de8e8046dc1c558465f74b4afe11d57cbc6cf3
      - patches/0011-revert_fp16_cast_syntax_change.patch
      - patches/clang14-fixes.patch
      # https://github.com/Homebrew/homebrew-core/pull/114739/files
      - patches/qt5-webengine-xcode14.diff

      # hmaarrfk - 2023/12
      #   I generated this patch when I updated the compilers on linux from 11 to 12
      #   during the libxml2212 migration
      #   https://github.com/conda-forge/qt-webengine-feedstock/pull/43/files
      #
      # Due to the limited access I have to osx and windows, I decided to only
      # apply this patch to linux.
      #
      # In searching the source for std::begin, it seemed like there were 100s
      # of occurances of its usage. I thus designed a command to help in its
      # replacement.
      # However, after applying the patch to the first error, it seemed like it worked.
      #
      # This patch was generated with
      # sed -i'' 's/std::begin[[:space:]]*(\([^)]*\))/(\1)/g' src/3rdparty/chromium/third_party/skia/src/utils/SkParseColor.cpp
      # sed -i'' 's/std::end[[:space:]]*(\([^)]*\))/(\1 + sizeof(\1) \/ sizeof(\1[0]))/g' src/3rdparty/chromium/third_party/skia/src/utils/SkParseColor.cpp
      - patches/cxx17_support_std_begin_std_end.patch  # [linux]

      # https://github.com/ninja-build/ninja/issues/2417#issuecomment-2059047539
      # https://bugs.gentoo.org/930107
      - patches/add_missing_dependency_on_spellcheck.diff

  - url: https://download.qt.io/development_releases/gnuwin32/gnuwin32.zip  # [win]
    folder: gnuwin32  # [win]
    sha256: 4a9dc893cc0a1695a16102a42ef47ef2e228652891f4afea67fadd452b63656b  # [win]

build:
  number: 7
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('qt-webengine', max_pin='x.x') }}
  missing_dso_whitelist:  # [osx]
    - /usr/lib/libbsm.0.dylib  # [osx]
    - /usr/lib/libcups.2.dylib  # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib/libsandbox.1.dylib  # [osx]
    - '/System/Library/Frameworks/CoreLocation.framework/**'  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
    - pkg-config                         # [unix]
    - make                               # [unix]
    - cmake
    - ninja
    - ruby >=2.5                         # [linux]
    - bison                              # [linux]
    - flex                               # [linux]
    - gperf                              # [linux]
    - perl 5
    - jom                                # [win]
    - nodejs >=16
  host:
    - libjpeg-turbo
    - pulseaudio-client                  # [linux]
    - pthread-stubs                      # [linux]
    - dbus                               # [linux]
    - fontconfig                         # [linux]
    - freetype                           # [linux]
    - libglib                            # [linux]
    - libxml2                            # [linux]
    - libxkbcommon                       # [linux]
    - libxkbfile                         # [linux]
    - expat                              # [linux]
    - libevent                           # [linux]
    - libpng
    - libiconv
    - nspr                               # [unix]
    - nss                                # [unix]
    - libsqlite
    - zlib
    - libxcb                             # [linux]
    - qt-main  {{ version }}
    - libwebp
    - libcups                            # [linux]
    # Found as part of 2023/04 exploration on overlinked dependencies
    - libopus                            # [linux]
    - harfbuzz                           # [linux]
    - alsa-lib                           # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxrender                    # [linux]
    - xorg-libxi                         # [linux]
    - xorg-libxcursor                    # [linux]
    - xorg-libxcomposite                 # [linux]
    - xorg-libxrandr                     # [linux]
    - xorg-libxtst                       # [linux]
    - xorg-xproto                        # [linux]
    - xorg-glproto                       # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-inputproto                    # [linux]
    - xorg-libxfixes                     # [linux]
  run:
    - libwebp
    # These do not have run_exports
    - xorg-libxcomposite                 # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libxrender                    # [linux]
    - xorg-libxrandr                     # [linux]
    - xorg-libxtst                       # [linux]
    - xorg-libxfixes                     # [linux]
  run_constrained:
    # As of, 2022/04/25, Qt 5.15.4 was only ever released to commercial
    # users. However it seems that qt webengine 5.15.4 sources were
    # released
    - qt 5.15.3|5.15.4|5.15.6|5.15.8
    # - qt {{ version }}

test:
  requires:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
    - make                               # [unix]
  files:
    - test/main-qtwebengine.cpp
    - test/qml.qrc
    - test/qrc_qml.cpp
    - test/main.qml
    - test/qtwebengine.pro

about:
  home: http://qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - duncanmmacleod
    - gillins
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
    - Tobias-Fischer
