{% set name = "qt-webengine" %}
{% set version = "5.15.4" %}
{% set version_major_minor = '.'.join(version.split('.')[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version_major_minor }}/{{ version }}/submodules/qtwebengine-everywhere-opensource-src-{{ version }}.tar.xz
    sha256: 8a2a903bcf2c45d8981f90fdfe96a9413d6fcfa0510e45c407a41a9b6bda0fca
    patches:
      - patches/0001-aarch64-sys-state-structs.patch                             # [aarch64]
      - patches/0002-macos-fatal-warnings.patch                                  # [osx]
      - patches/0003-Set-host-and-target-cpus-in-gn-build.patch                  # [arm64]
      - patches/0005-macos-use-CONDA_BUILD_SYSROOT.patch                         # [osx]
      - patches/0007-Compile-GN-to-support-both-x86_64-and-arm64-archs-wh.patch  # [arm64]
      # https://bugreports.qt.io/browse/QTBUG-101995?focusedCommentId=653798
      # https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/402639
      - patches/fix_unused_var_in_harfbuzz_ng.patch
      # This patch may be required for other OSes too
      # similar to the discussion in
      # https://github.com/abseil/abseil-cpp/issues/1275
      - patches/limits_h_header.patch
      # Only used in aarch64 / osx-arm
      # https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236855#c8
      #    reverts
      # https://github.com/qt/qtwebengine-chromium/commit/b2de8e8046dc1c558465f74b4afe11d57cbc6cf3
      - patches/0011-revert_fp16_cast_syntax_change.patch
      - patches/clang14-fixes.patch
      # https://github.com/Homebrew/homebrew-core/pull/114739/files
      - patches/qt5-webengine-xcode14.diff

  - url: https://download.qt.io/development_releases/gnuwin32/gnuwin32.zip  # [win]
    folder: gnuwin32  # [win]
    sha256: 4a9dc893cc0a1695a16102a42ef47ef2e228652891f4afea67fadd452b63656b  # [win]

build:
  number: 4
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('qt-webengine', max_pin='x.x') }}
  missing_dso_whitelist:  # [osx]
    - /usr/lib/libbsm.0.dylib  # [osx]
    - /usr/lib/libcups.2.dylib  # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib/libsandbox.1.dylib  # [osx]
    - '/System/Library/Frameworks/CoreLocation.framework/**'  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
    - pkg-config                         # [unix]
    - make                               # [unix]
    - cmake
    - ninja
    - ruby >=2.5                         # [linux]
    - bison                              # [linux]
    - flex                               # [linux]
    - gperf                              # [linux]
    - perl 5
    - jom                                # [win]
    - nodejs >=16
  host:
    # Chromium expects libjpeg-turbo as their main libjpeg reference and therefore
    # it will use an statically-linked version to it whilst
    # https://github.com/conda-forge/conda-forge.github.io/issues/673 is fixed.
    # Most internal dependencies such as SKIA use turbo-jpeg specific functions
    # and constants, and therefore trying to patch them would cause unexpected
    # errors or would be impossible.
    # - jpeg
    - pulseaudio                         # [linux]
    - gstreamer
    - pthread-stubs                      # [linux]
    - dbus                               # [linux]
    - fontconfig                         # [linux]
    - freetype                           # [linux]
    - gst-plugins-base
    - gstreamer
    - libglib                            # [linux]
    - libxml2                            # [linux]
    - libxkbcommon                       # [linux]
    - expat                              # [linux]
    - libevent                           # [linux]
    - libpng
    - libiconv
    - nspr                               # [unix]
    - nss                                # [unix]
    - libsqlite
    - zlib
    - libxcb                             # [linux]
    - qt-main
    - libwebp
    - libcups                            # [linux]
  run:
    - libwebp
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx and x86_64]
    # As of, 2022/04/25, Qt 5.15.4 was only ever released to commercial
    # users. However it seems that qt webengine 5.15.4 sources were
    # released
    - qt 5.15.3|5.15.4|5.15.6
    # - qt {{ version }}

test:
  requires:
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - make                               # [unix]
  files:
    - test/main-qtwebengine.cpp
    - test/qml.qrc
    - test/qrc_qml.cpp
    - test/main.qml
    - test/qtwebengine.pro

about:
  home: http://qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - duncanmmacleod
    - gillins
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
    - Tobias-Fischer
