context:
  version: "6.10.2"
  maj_min: ${{ (version | split('.'))[:2] | join('.') }}

package:
  name: qt6-webengine
  version: ${{ version }}

source:
  url: https://download.qt.io/official_releases/qt/${{ maj_min }}/${{ version }}/submodules/qtwebengine-everywhere-src-${{ version }}.tar.xz
  md5: cab991d3174f9039b94b46fd98b0cee1
  patches:
    - patches/0001-chromium-add-conda-CDT-include-paths-to-include_dirs.patch
    - patches/0002-add-system-lib-options-to-cmake-files.patch
    - patches/0003-allow-building-with-non-apple-clang-version.patch
    - patches/0004-chromium-force-settings-to-build-without-xcode.patch
    - patches/0005-set-rpath-on-generators-on-osx.patch
    - patches/0006-disable-newer-glibc-features.patch
    - patches/0007-chromium-fix-readelf-path.patch
    - patches/0008-use-binary-input-for-gperf-on-Windows.patch
    - patches/0009-Disable-ScreenCaptureKit-on-OSX.patch
    # Missing _GNU_SOURCE macro definition causes asprintf and vasprintf functions to be undeclared in glibc headers.
    # These are GNU extensions that require _GNU_SOURCE to be defined before including <stdio.h>.
    # qtwebengine/src/3rdparty/chromium/third_party/libdrm/src/xf86drm.c:362:9: error: implicit declaration of function 'asprintf'; did you mean 'vsprintf'?
    - patches/0010-Add-gnu-resource.patch

    # conda-forge specific patch to build with sysroot_linux 2.17.*
    - patches/0030-chromium-cos7.patch
    - patches/0031-chromium-v4l2.patch
    - patches/0032-chromium-v8.patch
    - patches/0033-chromium-sandbox.patch

build:
  number: 0
  skip:
    # requires libgbm
    - linux and aarch64
    # cannot cross-compile
    - osx and x86_64

requirements:
  build:
    - cmake
    - ninja
    - perl
    - nodejs >=24
    - html5lib
    - if: unix
      then:
        - bison
        - gperf
        - pkg-config
        # - libtool
      else:
        - winflexbison
        - m2-gperf
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then: qt6-main ${{ version }}.*
  host:
    - qt6-main ${{ version }}.*
    - if: linux
      then:
        - dbus
        - alsa-lib
        - expat
        - fontconfig
        - libcups
        - libdrm
        - libgl-devel
        - libglx-devel
        #- libprotobuf
        - libxcb
        - libxkbcommon
        - libxkbfile
        - nspr
        - nss
    - if: unix
      then:
        - lcms2
        - freetype
    - glib
    - html5lib
    - harfbuzz
    # - lcms2
    - libevent
    - libtiff
    - libpng
    - if: unix
      then:
        - libopus
        - libvpx
    - if: linux
      then:
        - libudev
        - libxkbfile
        - libopengl-devel
        - xorg-libxshmfence
    - if: not osx
      then:
        - libvulkan-headers
        - libvulkan-loader
    - libxml2-devel
    - libxslt
    - openjpeg
    - re2
    - snappy
    - minizip
    - zlib
  run:
    - qt6-main ${{ version }}.*
  run_exports:
    - ${{ pin_subpackage('qt6-webengine', upper_bound='x.x') }}

tests:
  - script:
      - if: unix
        then:
          - test -d $PREFIX/include/qt6/QtWebEngineWidgets
          - test -d $PREFIX/include/qt6/QtPdfWidgets
          - test -f $PREFIX/lib/libQt6WebEngineWidgets${SHLIB_EXT}
          - test -f $PREFIX/lib/libQt6PdfWidgets${SHLIB_EXT}
        else:
          - if not exist %PREFIX%\\Library\\include\\qt6\\QtWebEngineWidgets exit 1
          - if not exist %PREFIX%\\Library\\lib\\Qt6WebEngineWidgets.lib exit 1
          - if not exist %PREFIX%\\Library\\bin\\Qt6WebEngineWidgets.dll exit 1
    requirements:
      run:
        - ${{ stdlib("c") }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - if: unix
          then:
            - make
            - pkg-config
    files:
      recipe:
        - test/main-qtwebengine.cpp
        - test/qml.qrc
        - test/qrc_qml.cpp
        - test/main.qml
        - test/qtwebengine.pro

about:
  homepage: http://qt-project.org
  license: BSD-3-Clause
  license_file: LICENSE.Chromium
  summary: Qt WebEngine
  description: |
    Provides support for web applications using the Chromium browser project.
  documentation: http://doc.qt.io/
  repository: https://github.com/qt/qtwebengine

extra:
  recipe-maintainers:
    - conda-forge/qt-main
  feedstock-name: qt-webengine
