azure:
  settings_linux:
    timeoutInMinutes: 60
  settings_osx:
    timeoutInMinutes: 60
  settings_win:
    timeoutInMinutes: 60
    variables:
      CONDA_BLD_PATH: C:\bld\
      MINIFORGE_HOME: C:\Miniforge
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native_and_emulated
