azure:
  store_build_artifacts: true
  # settings_linux:
  #   timeoutInMinutes: 1
  # settings_osx:
  #   timeoutInMinutes: 1
  settings_win:
    # timeoutInMinutes: 1
    variables:
      CONDA_BLD_PATH: C:\bld\
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
test_on_native_only: true
