conda_forge_output_validation: true
azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
provider:
  linux_aarch64: azure
os_version:
  linux_64: cos7
build_platform:
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
